Random forest is a collection of multiple decision trees

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [40]:
data = pd.read_csv('laptop_buying_data.csv',na_values=[""," ","NA","N/A","null","NULL","none","?"])
data.head()

    Age  Income Student  Credit Score  Location Buys Laptop
0  25.0    High      No         700.0     Urban         Yes
1  30.0    High     Yes         650.0     Urban          No
2  22.0     Low      No         580.0     Rural          No
3  35.0  Medium      No         620.0     Urban         Yes
4  28.0     Low     Yes         690.0  Suburban         Yes

Doing data inspection

In [41]:
data.shape

(52, 6)

In [42]:
data.columns.tolist()

['Age', 'Income', 'Student', 'Credit Score', 'Location', 'Buys Laptop']

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           51 non-null     float64
 1   Income        50 non-null     object
 2   Student       51 non-null     object
 3   Credit Score  50 non-null     float64
 4   Location      51 non-null     object
 5   Buys Laptop   52 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.6+ KB

In [44]:
data.isnull().sum()

Age             1
Income          2
Student         1
Credit Score    2
Location        1
Buys Laptop     0
dtype: int64

In [45]:
data = data.dropna()

In [46]:
data.isnull().sum()

Age             0
Income          0
Student         0
Credit Score    0
Location        0
Buys Laptop     0
dtype: int64

In [47]:
data = data.drop_duplicates()

In [48]:
data.describe(include = 'all')

              Age Income Student  Credit Score Location Buys Laptop
count   43.000000     43      43     43.000000       43          43
unique        NaN      3       2           NaN        3           2
top           NaN    Low      No           NaN    Urban         Yes
freq          NaN     15      26           NaN       19          31
mean    31.395349    NaN     NaN    676.162791      NaN         NaN
std      6.990264    NaN     NaN     67.628513      NaN         NaN
min     20.000000    NaN     NaN    560.000000      NaN         NaN
25%     26.000000    NaN     NaN    622.500000      NaN         NaN
50%     30.000000    NaN     NaN    665.000000      NaN         NaN
75%     36.500000    NaN     NaN    725.000000      NaN         NaN
max     46.000000    NaN     NaN    810.000000      NaN         NaN

Seperate X input features and output y

In [56]:
X = data.drop('Buys Laptop',axis = 1)
y = data['Buys Laptop']

numeric_features = ['Age','Credit Score']
categorical_features = ['Income','Student','Location']

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42, stratify = y)

In [58]:
from sklearn.impute import SimpleImputer
numeric_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy = 'median'))
])
categorical_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy = 'most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown = 'ignore'))
])

In [59]:
preprocessor = ColumnTransformer([
    ('num',numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

model = Pipeline([
    ('prepocessor',preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators = 200,
        max_depth = 6,
        random_state = 42
    ))
])

In [60]:
model.fit(X_train, y_train)

Pipeline(steps=[('prepocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Age', 'Credit Score']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Income', 'Student',
                                                   'Location'])])),
                ('classifier',
                 RandomForestClassifier(max_depth=6, n_estimators=200,
                                        random_state=42))])

In [61]:
y_pred = model.predict(X_test)
print(y_pred)

['Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No']

In [63]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: ',round(accuracy,2))

Accuracy:  1.0