In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import random

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
n = 120

age = np.random.randint(18,61,n)
income = np.random.normal(55000, 15000, n).clip(20000, 120000)
purchases = np.random.poisson(5,n) + 1
spending = (income + np.random.uniform(0.02, 0.10 ,n) + purchases * np.random.uniform(150,500, n))

satisfaction = np.random.normal(7,1.2, n).clip(1,10)

df = pd.DataFrame({'Cus_ID': range(1, n + 1),
                   'Age' : age,
                   'Monthly_Income' : income.round(0),
                   'Purchases' : purchases,
                'Total_Spending' : spending.round(0),
                'Satisfaction_score' : satisfaction.round(0)})

In [8]:
df.head()

   Cus_ID  Age  Monthly_Income  Purchases  Total_Spending  Satisfaction_score
0       1   60         53074.0          6         54924.0                 6.0
1       2   23         76633.0          8         79625.0                 8.0
2       3   55         76317.0          4         77921.0                 7.0
3       4   41         82776.0         10         86264.0                 7.0
4       5   53         46800.0          6         49397.0                 8.0

In [9]:
df.shape

(120, 6)

In [10]:
mean_spending = df['Total_Spending'].mean()
mean_spending

np.float64(57564.183333333334)

In [14]:
median_spending = df['Total_Spending'].median()
print(f'Median spending = {median_spending:,.2f}')

Median spending = 57,343.50

In [15]:
print('Purchase count frequencies: ')
print(df['Purchases'].value_counts().sort_index())

Purchase count frequencies:
Purchases
1      1
2      3
3     10
4     12
5     28
6     17
7     14
8     15
9      7
10     5
11     5
12     2
13     1
Name: count, dtype: int64

In [16]:
mode_purchases = df['Purchases'].mode()[0]
print(f"Most common number of purchase = {mode_purchases}")

Most common number of purchase = 5

In [18]:
income_range = df['Monthly_Income'].max() - df['Monthly_Income'].min()
income_range

np.float64(76626.0)

In [20]:
income_variance = df["Monthly_Income"].var()
income_variance

np.float64(227490138.33361346)

In [21]:
income_std = df['Monthly_Income'].std()
income_std

np.float64(15082.776214398113)

Normal distribution is a bell shaped symmetric curve which tells us that our data is normally distributed.

In [1]:
print('Hello World')

Hello World